
links= [
        'https://www.ncaa.com/news/basketball-men/article/2020-05-08/2015-ncaa-tournament-bracket-scores-stats-records',
        'https://www.ncaa.com/news/basketball-men/article/2020-05-07/2016-ncaa-tournament-bracket-scores-stats-records', 
        'https://www.ncaa.com/news/basketball-men/article/2020-05-06/2017-ncaa-tournament-bracket-scores-stats-records',
        'https://www.ncaa.com/news/basketball-men/article/2020-05-06/2018-ncaa-tournament-bracket-scores-stats-records',
        'https://www.ncaa.com/news/basketball-men/article/2020-05-06/2019-ncaa-tournament-bracket-scores-stats-records',
        'https://www.ncaa.com/news/basketball-men/article/2022-07-20/2021-ncaa-bracket-scores-stats-records-march-madness-mens-tournament',
        'https://www.ncaa.com/news/basketball-men/article/2022-07-12/2022-ncaa-bracket-mens-march-madness-scores-stats-records',
        'https://www.ncaa.com/news/basketball-men/article/2023-04-18/2023-ncaa-bracket-scores-stats-march-madness-mens-tournament',
        'https://www.ncaa.com/news/basketball-men/article/2024-12-06/2024-ncaa-bracket-scores-stats-march-madness-mens-tournament'
        ]

CONVERT_NCAA = {
    "Northern Ariz.": "Northern Arizona",
    "McNeese": "McNeese St.",
    "N.C. A&T": "North Carolina A&T",
    "Greensboro": "UNC Greensboro",
    "Alcorn": "Alcorn St.",
    "South Fla.": "South Florida",
    "Fla. Atlantic": "Florida Atlantic",
    "Grambling": "Grambling St.",
    "Eastern Mich.": "Eastern Michigan",
    "Charleston So.": "Charleston Southern",
    "Southern U.": "Southern",
    "Northern Ky.": "Northern Kentucky",
    "ETSU": "East Tennessee St.",
    "Eastern Ky.": "Eastern Kentucky",
    "UNI": "Northern Iowa",
    "ULM": "Louisiana Monroe",
    "Southern Miss.": "Southern Miss",
    "Southeast Mo. St.": "Southeast Missouri St.",
    "Bethune-Cookman": "Bethune Cookman",
    "Southern California": "USC",
    "NC State": "N.C. State",
    "A&M-Corpus Christi": "Texas A&M Corpus Chris",
    "FDU": "Fairleigh Dickinson",
    "CSUN": "Cal St. Northridge",
    "Central Ark.": "Central Arkansas",
    "UMES": "Maryland Eastern Shore",
    "CSU Bakersfield": "Cal St. Bakersfield",
    "Middle Tenn.": "Middle Tennessee",
    "Army West Point": "Army",
    "Ole Miss": "Mississippi",
    "St. John's (NY)": "St. John's",
    "Miami (OH)": "Miami OH",
    "Prairie View": "Prairie View A&M",
    "Ark.-Pine Bluff": "Arkansas Pine Bluff",
    "UConn": "Connecticut",
    "UIW": "Incarnate Word",
    "UTRGV": "UT Rio Grande Valley",
    "Nicholls": "Nicholls St.",
    "UIC": "Illinois Chicago",
    "N.C. Central": "North Carolina Central",
    "Western Caro.": "Western Carolina",
    "Central Mich.": "Central Michigan",
    "Miami (FL)": "Miami FL",
    "Gardner-Webb": "Gardner Webb",
    "Seattle U": "Seattle",
    "Loyola Maryland": "Loyola MD",
    "UAlbany": "Albany",
    "Eastern Wash.": "Eastern Washington",
    "Southeastern La.": "Southeastern Louisiana",
    "Ga. Southern": "Georgia Southern",
    "Southern Ill.": "Southern Illinois",
    "SIUE": "SIU Edwardsville",
    "Lamar University": "Lamar",
    "Western Ky.": "Western Kentucky",
    "Boston U.": "Boston University",
    "Northern Colo.": "Northern Colorado",
    "Central Conn. St.": "Central Connecticut",
    "UT Martin": "Tennessee Martin",
    "Omaha": "Nebraska Omaha",
    "Col. of Charleston": "Charleston",
    "IU Indy": "IUPUI",
    "Western Ill.": "Western Illinois",
    "SFA": "Stephen F. Austin",
    "Eastern Ill.": "Eastern Illinois",
    "Sam Houston": "Sam Houston St.",
    "App State": "Appalachian St.",
    "LMU (CA)": "Loyola Marymount",
    "Western Mich.": "Western Michigan",
    "Mississippi Val.": "Mississippi Valley St.",
    "UNCW": "UNC Wilmington",
    "Saint Mary's (CA)": "Saint Mary's",
    "FGCU": "Florida Gulf Coast",
    "NIU": "Northern Illinois",
    "Texas A&M-CC": "Texas A&M Corpus Chris",
    "Hawai'i": "Hawaii",
    "Miami (Fla.)": "Miami FL",
    "Arkansas-Pine Bluff": "Arkansas Pine Bluff",
    "UCSB": "UC Santa Barbara",
    "Miami": "Miami FL",
    "Pennsylvania": "Penn",
    "Loyola Chi.": "Loyola Chicago",
    "Col of Charleston": "College of Charleston",
    "S. Dakota St.": "South Dakota St.",
    "FAU": "Florida Atlantic",
    "North Kentucky": "Northern Kentucky",
    "St. Mary’s": "Saint Mary's" ,
    
}
FINAL_CONVERT = {
    "Pitt": "Pittsburgh",
    "UMass": "Massachusetts",
    "St. Peter's": "Saint Peter's",
    "College of Charleston": "Charleston",
    "Notre": "Notre Dame",
    "N. Carolina": "North Carolina",

}
Schools = [

   [
    "Kentucky", "Hampton", "Kansas", "New Mexico St.", "Notre Dame", "Northeastern", "Maryland", "Valparaiso", 
    "West Virginia", "Buffalo", "Butler", "Texas", "Wichita St.", "Indiana", "Cincinnati", "Purdue", "Wisconsin", 
    "Coastal Carolina", "Arizona", "Texas Southern", "Georgia St.", "Baylor", "North Carolina", "Harvard", "Arkansas", 
    "Wofford", "Xavier", "Ole Miss", "Ohio St.", "VCU", "Oregon", "Oklahoma St.", "Villanova", "Lafayette", "Virginia", 
    "Belmont", "Oklahoma", "Albany", "Louisville", "UC Irvine", "Northern Iowa", "Wyoming", "Dayton", "Providence", 
    "Michigan St.", "Georgia", "NC State", "LSU", "Duke", "Robert Morris", "Gonzaga", "North Dakota St.", "UAB", 
    "Iowa St.", "Georgetown", "Eastern Washington", "Utah", "Stephen F. Austin", "UCLA", "SMU", "Iowa", "Davidson", 
    "San Diego St.", "St. John's"
   ],

   [
    "North Carolina", "Florida Gulf Coast", "Xavier", "Weber St.", "Stephen F. Austin", "West Virginia",
    "Kentucky", "Stony Brook", "Indiana", "Chattanooga", "Notre Dame", "Michigan",
    "Wisconsin", "Pittsburgh", "Providence", "Southern California", "Oregon", "Holy Cross",
    "Oklahoma", "Cal St. Bakersfield", "Texas A&M", "Green Bay", "Duke", "UNC Wilmington",
    "Yale", "Baylor", "Northern Iowa", "Texas", "VCU", "Oregon St.",
    "Saint Joseph's", "Cincinnati", "Kansas", "Austin Peay", "Villanova", "UNC Asheville",
    "Miami (Fla.)", "Buffalo", "Hawai'i", "California", "Maryland", "South Dakota St.",
    "Wichita St.", "Arizona", "Iowa", "Temple", "UConn", "Colorado",
    "Virginia", "Hampton", "Middle Tennessee", "Michigan St.", "Utah", "Fresno St.",
    "Iowa St.", "Iona", "Little Rock", "Purdue", "Gonzaga", "Seton Hall",
    "Syracuse", "Dayton", "Butler", "Texas Tech"
   ],

   [
    "Villanova", "Mount St. Mary's", "Duke", "Troy", "Baylor", "New Mexico St.", "Florida", "East Tennessee St.",
    "Virginia", "UNC Wilmington", "Southern California", "SMU", "South Carolina", "Marquette", "Wisconsin", "Virginia Tech",
    "Gonzaga", "South Dakota St.", "Arizona", "North Dakota", "Florida St.", "Florida Gulf Coast", "West Virginia", "Bucknell",
    "Notre Dame", "Princeton", "Xavier", "Maryland", "Saint Mary's", "VCU", "Northwestern", "Vanderbilt",
    "North Carolina", "Texas Southern", "Kentucky", "Northern Kentucky", "UCLA", "Kent St.", "Butler", "Winthrop",
    "Middle Tennessee", "Minnesota", "Cincinnati", "Kansas St.", "Wichita St.", "Dayton", "Arkansas", "Seton Hall",
    "Kansas", "UC Davis", "Louisville", "Jacksonville St.", "Oregon", "Iona", "Purdue", "Vermont",
    "Iowa St.", "Nevada", "Rhode Island", "Creighton", "Michigan", "Oklahoma St.", "Michigan St.", "Miami (Fla.)"
   ],  

   [ 
    "Villanova", "Radford", "Purdue", "Cal St. Fullerton", "Texas Tech", "Stephen F. Austin", 
    "Marshall", "Wichita St.", "West Virginia", "Murray St.", "Florida", "St. Bonaventure", 
    "Butler", "Arkansas", "Alabama", "Virginia Tech",
    "Xavier", "Texas Southern", "North Carolina", "Lipscomb", "Michigan", "Montana", "Gonzaga", 
    "UNC Greensboro", "Ohio St.", "South Dakota St.", "Houston", "San Diego St.", 
    "Texas A&M", "Providence", "Florida St.", "Missouri", "UMBC", "Virginia", "Cincinnati", 
    "Georgia St.", "Tennessee", "Wright St.", "Buffalo", "Arizona", "Kentucky", "Davidson", 
    "Loyola Chicago", "Miami (Fla.)", "Nevada", "Texas", "Kansas St.", "Creighton", "Kansas", 
    "Pennsylvania", "Duke", "Iona", "Michigan St.", "Bucknell", "Auburn", "College of Charleston", 
    "Clemson", "New Mexico St.", "Syracuse", "TCU", "Rhode Island", "Oklahoma", "Seton Hall", 
    "NC State"
    ],
   [
    "Duke", "North Dakota St.", "Michigan St.", "Bradley", "LSU", "Yale", 
    "Virginia Tech", "Saint Louis", "Liberty", "Mississippi St.", "Maryland", "Belmont", 
    "Minnesota", "Louisville", "UCF", "VCU",
    "Gonzaga", "Fairleigh Dickinson", "Michigan", "Montana", "Texas Tech", "Northern Kentucky", 
    "Florida St.", "Vermont", "Murray St.", "Marquette", "Buffalo", "Arizona St.", 
    "Florida", "Nevada", "Baylor", "Syracuse",
    "Virginia", "Gardner-Webb", "Tennessee", "Colgate", "Purdue", "Old Dominion", "UC Irvine", 
    "Kansas St.", "Oregon", "Wisconsin", "Villanova", "Saint Mary's", "Iowa", "Temple", 
    "Oklahoma", "Ole Miss",
    "North Carolina", "Iona", "Kentucky", "Abilene Christian", "Houston", "Georgia St.", 
    "Kansas", "Northeastern", "Auburn", "New Mexico St.", "Ohio St.", "Iowa St.", 
    "Wofford", "Seton Hall", "Washington", "Utah St."
    ],
    [
    "Illinois", "Drexel", "Loyola Chicago", "Georgia Tech", "Oregon St.", "Tennessee", 
    "Oklahoma St.", "Liberty", "Syracuse", "San Diego St.", "West Virginia", "Morehead St.", 
    "Rutgers", "Clemson", "Houston", "Cleveland St.", "Gonzaga", "Norfolk St.", "Oklahoma", 
    "Missouri", "Creighton", "UCSB", "Ohio", "Virginia", "USC", "Drake", "Kansas", 
    "Eastern Wash.", "Oregon", "VCU", "Iowa", "Grand Canyon", "Michigan", "Texas Southern", 
    "LSU", "St. Bonaventure", "Colorado", "Georgetown", "Florida St.", "UNC Greensboro", 
    "UCLA", "BYU", "Abilene Christian", "Texas", "Maryland", "UConn", "Alabama", "Iona", 
    "Baylor", "Hartford", "Wisconsin", "North Carolina", "Villanova", "Winthrop", "North Texas", 
    "Purdue", "Texas Tech", "Utah St.", "Arkansas", "Colgate", "Florida", "Virginia Tech", 
    "Oral Roberts", "Ohio St."
    ],
    [
    "Kansas", "Texas Southern", "Creighton", "San Diego St.", "Richmond", "Iowa", "Providence", 
    "S. Dakota St.", "Iowa St.", "LSU", "Wisconsin", "Colgate", "Miami (FL)", "USC", "Auburn", 
    "Jacksonville St.", "Gonzaga", "Georgia St.", "Memphis", "Boise St.", "New Mexico St.", 
    "UConn", "Arkansas", "Vermont", "Notre Dame", "Alabama", "Texas Tech", "Montana St.", 
    "Michigan St.", "Davidson", "Duke", "Cal St. Fullerton", "Baylor", "Norfolk St.", 
    "North Carolina", "Marquette", "Saint Mary’s", "Indiana", "UCLA", "Akron", "Texas", 
    "Virginia Tech", "Purdue", "Yale", "Murray St.", "San Francisco", "St. Peter’s", "Kentucky",
     "Arizona", "Wright St.", "TCU", "Seton Hall", "Houston", "UAB", "Illinois", "Chattanooga", 
    "Michigan", "Colorado St.", "Tennessee", "Longwood", "Ohio St.", "Loyola Chicago", 
    "Villanova", "Delaware"
    ],
    [
    "Houston", "North Kentucky", "Auburn", "Iowa", "Miami (FL)", "Drake", "Indiana", "Kent St.", 
    "Pitt", "Iowa St.", "Xavier", "Kennesaw St.", "Penn St.", "Texas A&M", "Texas", "Colgate", 
    "Kansas", "Howard", "Arkansas", "Illinois", "St. Mary’s", "VCU", "UConn", "Iona", 
    "TCU", "Arizona St.", "Gonzaga", "Grand Canyon", "Northwestern", "Boise St.", "UCLA", 
    "UNC Asheville", "FDU", "Purdue", "FAU", "Memphis", "Duke", "Oral Roberts", "Tennessee", 
    "Louisiana", "Kentucky", "Providence", "Kansas St.", "Montana St.", "Michigan St.", 
    "USC", "Marquette", "Vermont", "Alabama", "Texas A&M-CC", "Maryland", "West Virginia", 
    "San Diego St.", "Col of Charleston", "Furman", "Virginia", "Creighton", "NC State", 
    "Baylor", "UCSB", "Missouri", "Utah St.", "Princeton", "Arizona"
    ],
    [
    "UConn", "Stetson", "Florida Atlantic", "UAB", "Yale", "Auburn", "Duquesne", "BYU", 
    "Illinois", "Morehead St.", "Washington St.", "Drake", "Iowa St.", "South Dakota St.", "North Carolina", "Wagner", 
    "Michigan St.", "Mississippi St.", "Grand Canyon", "Saint Mary's", "Alabama", "Charleston", "Clemson", "New Mexico", 
    "Baylor", "Colgate", "Dayton", "Nevada", "Northwestern", "Arizona", "Long Beach St.", 
    "Houston", "Longwood", "Texas A&M", "Nebraska", "James Madison", "Wisconsin", "Duke", "Vermont", 
    "NC State", "Texas Tech", "Oakland", "Kentucky", "Colorado", "Florida", 
    "Western Kentucky", "Marquette", "Purdue", "Grambling St.", "Utah St.", "TCU", "Gonzaga", 
    "McNeese", "Kansas", "Samford", "Oregon", "South Carolina", "Creighton", 
    "Akron", "Texas", "Colorado St.", "Tennessee", "Saint Peter's"
    ]
    ]
